security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        ldap_users:
            ldap:
                service: Symfony\Component\Ldap\Ldap
                base_dn: '%env(LDAP_BASE_DN)%'
                search_dn: '%env(LDAP_SEARCH_DN)%'
                search_password: '%env(LDAP_SEARCH_PASSWORD)%'
                default_roles: ROLE_USER
                uid_key: '%env(LDAP_UID_KEY)%'

    firewalls:
        login:
            pattern: ^/login
            stateless: true
            provider: ldap_users
            json_login:
                check_path: /login
                username_path: username
                password_path: password
            custom_authenticators:
                - App\Security\LdapAuthenticator

        api:
            pattern: ^/
            stateless: true
            jwt: ~

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: ROLE_USER }
